//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUM.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public long UserID { get; set; }
        public string Address1 { get; set; }
        public string PinCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int DefaultAddress { get; set; }
    
        public virtual User User { get; set; }
    }
}
